### ISSUE TITLE
Quesiton about github action responder

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/buffy#36]
hey @xuanxu 👋 i added a github action responded to trigger our update [contributors workflow](https://github.com/pyOpenSci/pyopensci.github.io/actions/runs/8903402667) (which i need to fix - there is a bug). 

I noticed that it isn't triggering the workflow. Is there something specific that i need to do to get that action to trigger when someone runs `@pyosbot update website` - you can see where i called the command [here](https://github.com/pyOpenSci/test-pyos-review/issues/22#issuecomment-2099294307) and the bot is still working as the help command works!

**Comment by xuanxu** [comment]
The config file looks good, this is most probably a permissions issue.
I'm reading [here](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) that the bot's token needs the `repo` scope. Can you check it has it?
If it is already there then I'd guess the bot has to be admin of the `pyOpenSci/pyopensci.github.io` repository.

**Comment by lwasser** [comment]
amazing. i didn't consider permissions. i just granted the bot maintainer level permissions to that repo and it ran!

**Comment by lwasser** [comment]
thank you!!

**Comment by lwasser** [comment]
ok i'll close this given it's working now 🚀 . i have a few more questions that i'll ask separately!
