### ISSUE TITLE
How to figure out what in the config yaml file broke the bot?

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/buffy#7]
hey @xuanxu i sent you a slack message but it might be nice to chat here openly. it seems like there are specific things in the YAML file that cause the bot to not respond. However i'm not sure how to identify what i've done wrong to break things.

i wondered if you could help me understand how to troubleshoot? it's probably hard to see if all tests  pass but the bot doesn't respond. One issue was the steps having the same name. i think i've fixed that. but now it's broken again and i'm not sure what i did. i obviously did something however.

**Comment by xuanxu** [comment]
Hey!
When the bot responds to simple commands (help, hi...) but there is a specific command where it goes silent, then probably that command is wrongly configured. But when the bot does not respond to anything usually there is something wrong in the YAML file. 
The two more common causes of YAML-parsing errors are:
 - Invalid indentation: if tabs are added where yaml expects a couple of spaces the file becomes invalid/unparseable. We have to make sure we use the same indentation already present in the file, in this case 2 spaces.
 - Wrong keys: if you use an arbitrary string for a responder, that will not be recognized and the loading of the YAML file will fail. To get the exact error line of the deployed bot, you have to take a look at the logs at Heroku. You can also check you are using only available keys. see documentation here: https://buffy.readthedocs.io/en/latest/available_responders.html

Currently the test suite covers the internal code, it runs the Buffy' specs as a bots generator, it does not validate individual bot config files.

**Comment by xuanxu** [comment]
Another tool for debugging is the webhook delivery log, where you can see the server response and redeliver any past request. https://github.com/pyOpenSci/test-pyos-review/settings/hooks

**Comment by lwasser** [comment]
thank you @xuanxu !!! i understand now!

**Comment by lwasser** [comment]
closing this as answered!
